### ISSUE TITLE
Deletion API docs are outdated

### ISSUE THREAD

**Issue by esproul** [circonus/irondb-docs#22]
Per @vasuraman11:

IRONdb docs in delete-text.md and delete-histogram.md are out-of-date.  All of the delete APIs are consistent and follow the nnt documentation, where the URI is:
`<nnt|text|histogram>/<check_uuid_regex>/<metric>`
and the end delete time is passed in the headers as:
`x-snowth-delete-time` (end time for deletion in seconds from epoch OR "all")
There is also an optional header value:
`x-snowth-full-delete` (if set to 1 means replicate the delete across nodes, by default the metric data is only deleted locally)

Also, delete-nnt.md needs to have the part removed about omitting the metric deleting the entire check, since that action is broken for nntbs and so I'll be removing the option to omit the metric name in the API completely (since I am told nobody uses it and fixing it would involve some difficulty because we'd have to search surrogate for all metrics belonging to a particular check).

**Comment by esproul** [comment]
@vasuraman11 the `x-snowth-full-delete` header has not been documented previously.  Is it new? Does it apply to all of the data types?

**Comment by vasuraman11** [comment]
git blame tells me that it was last modified (or put in) by Riley 2 months ago as part of tag search #1042
it is valid for all types excepting sweep delete (so DELETE on nnt, text and hist )
